CREATE TABLE customers (
    customer_id SERIAL PRIMARY KEY,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    country VARCHAR(50) DEFAULT 'Germany',
    signup_date DATE DEFAULT CURRENT_DATE
);
CREATE TABLE products (
    product_id SERIAL PRIMARY KEY,
    product_name VARCHAR(100) NOT NULL,
    category VARCHAR(50),
    price NUMERIC(10, 2) NOT NULL,
    stock_quantity INTEGER NOT NULL DEFAULT 0
);
CREATE TABLE orders (
    order_id SERIAL PRIMARY KEY,
    customer_id INTEGER REFERENCES customers(customer_id),
    product_id INTEGER REFERENCES products(product_id),
    quantity INTEGER NOT NULL,
    order_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
INSERT INTO customers (first_name, last_name, email, country) VALUES
('Lauraine', 'Kadjio', 'lauraine.test@fau.de', 'Germany'),
('Thomas', 'Müller', 'thomas.mueller@web.de', 'Germany'),
('Sarah', 'Smith', 'sarah.smith@gmail.com', 'United Kingdom');

INSERT INTO products (product_name, category, price, stock_quantity) VALUES
('Mechanical RGB Keyboard', 'Accessories', 89.99, 50),
('Wireless Mouse', 'Accessories', 49.50, 120),
('27-Inch 4K Monitor', 'Monitors', 349.99, 15);

INSERT INTO orders (customer_id, product_id, quantity) VALUES
(1, 1, 1), -- Lauraine buys 1 keyboard
(2, 2, 2), -- Thomas buys 2 mice
(2, 3, 1); -- Thomas buys 1 monitor

SELECT * FROM customers;
-- Filtering the customer list to isolate users living in Germany.
SELECT * FROM customers 
WHERE country = 'Germany';

SELECT 
    orders.order_id,
    customers.first_name,
    products.product_name,
    orders.quantity
FROM orders
INNER JOIN customers ON orders.customer_id = customers.customer_id
INNER JOIN products ON orders.product_id = products.product_id;

-- Revenue generated by each individual order line
SELECT 
    orders.order_id,
    customers.first_name,
    products.product_name,
    orders.quantity,
    products.price AS unit_price,
    (orders.quantity * products.price) AS total_revenue
FROM orders
INNER JOIN customers ON orders.customer_id = customers.customer_id
INNER JOIN products ON orders.product_id = products.product_id;

-- Grouping data by customer to calculate total spending and order frequency.
SELECT 
    customers.customer_id,
    customers.first_name,
    customers.country,
    SUM(orders.quantity * products.price) AS total_spent,
    COUNT(orders.order_id) AS total_orders
FROM customers
LEFT JOIN orders ON customers.customer_id = orders.customer_id
LEFT JOIN products ON orders.product_id = products.product_id
GROUP BY customers.customer_id, customers.first_name, customers.country
ORDER BY total_spent DESC;
